silverstripe/cwp-recipe-kitchen-sink

- .travis.yml
- composer.json
- phpunit.xml.dist
This adds a Travis build for each recipe in the CWP "kitchen sink".
Note: the recipe-core testsuite times out taking far too long to run. We may need to split it up into shorter test suites.
> Add phpunit testsuites for each recipe and add to Travis builds

- composer.json
This PR adds the recipe-testing as a dev dependency. Amongst others, this includes behat-extension.
> NEW Add recipe-testing dev dependency

- .cow.json
This will ensure that other changes are always included in CWP changelogs without needing to remember to add the CLI argument.
Issue: https://github.com/silverstripe/cow/issues/122
> Add cow config for changelog holder, path, and include-other-changes

- .gitignore
- app/_config/theme.yml
Fixes #28 
By having this file in the project already, it shouldn't be added automatically by the cwp-installer's project-files and will be skipped in favour of the existing file.
> Enable watea theme by default in kitchen sink

- .changelog.md.twig
- .cow.json
This template is used by Cow to populate fresh changelogs. I've written it to roughly match the format we've been following in recent releases.
> Add changelog template

- .changelog.md.twig
Adding additional information to the change log template to better match the recent 2.3 release and the suggested changes in https://github.com/silverstripe/cwp/issues/188
> DOCS new headings for change log template

- .travis.yml
- composer.json
- phpunit.xml.dist
This adds the MFA dependencies for any builds running PHP 7.1. In CWP 2.4 this will be part of composer.json, since it will require PHP 7.1 as a minimum.
Fixes https://github.com/silverstripe/cwp-recipe-kitchen-sink/issues/33
I'll adjust any test failures, reference this PR, and re-run the failures until green then self merge it.
> Add inline requirements for MFA modules in Travis builds for PHP 7.1

- app/_config/agencyextensions.yml
This is a kitchen sink, so optional stuff should be enabled, right?
> Enable color and font pickers by default

- .changelog.md.twig
For release candidates, we don't need to provide a full set of information in the changelog, so this currently gets removed by hand after generation.
Now that [we can access the full `Version` object](https://github.com/silverstripe/cow/pull/157), we can provide a special message in release candidates, and output the existing sections only in stable releases.
> DOC Adjust changelog template for RC releases

- .travis.yml
- phpunit.xml.dist
a) Fixes travis tests that were running out of memory
b) Excludes queued jobs tests that were only failing on the 2.2 branch of kitchen-sink.  They pass fine in 2.3 and if you run the tests on the queuedjobs module by itself
Will merge this up to 2.3 and then revert the unit test exclusions so they're still included in kitchen-sink 2.3 and beyond.
Will keep the 3G memory in 2.3 and beyond because there's some tests in 2.3 that are running out of memory
> Increase travis memory to 3G

- phpunit.xml.dist
Follow on from https://github.com/silverstripe/cwp-recipe-kitchen-sink/pull/52 which:
a) increased travis memory to 3G
b) excluded some queuedjob tests from running which were only broken on 2.2 (not 2.3)
This PR:
a) includes a merge up from 2.2 to 2.3 so that travis memory is now 3G
b) re-includes the queued jobs tests since they do pass on 2.3
> Increase travis memory to 3G and re-include queuedjobs tests

- composer.json
Specify php 7.1 as the required version
This should prompt cow to use php 7.1 instead of php 7.3 so that the realme module (php <=7.1) can be installed
> Specify php 7.1

- .travis.yml
- composer.json
RealMe is known not to be compatible with 7.2+ yet, so I've pinned the authenticator test suite to 7.1 for the time being.
> Bump all matrix entries except authenticators to PHP 7.4

- .changelog.md.twig
One sentence really needed a re-work, so I've also updated 'Silverstripe' to match recent branding changes. We'd be doing the same in future release announcements too.
> DOCS new branding in cwp change log template

- composer.json
Although framework still supports 5.6, mfa requires 7.1
> Update PHP to 7.1

- phpunit.xml.dist
This side steps a silly problem in SearchFormTest. SearchFormTest enable FulltextSeacrhable which can not be disabled and interferes with fixtures creations an later tests.
* https://github.com/silverstripe/silverstripe-asset-admin/issues/813
> Reorder recipe-cms test suite to bypass a silly problem with SearchFormTest

- composer.json
.travis.yml had no required changes
```
before_script:
- phpenv rehash
- phpenv config-rm xdebug.ini || true
- echo 'memory_limit = 2G' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
- composer validate
- composer install --prefer-source --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile
- composer global require silverstripe/cow ^2
- $HOME/.composer/vendor/bin/cow schema:validate
script:
- if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit --testsuite "$PHPUNIT_TEST" --exclude-group exclude-from-travis; fi
```
> Update for 2.6

- composer.json
Include silverstripe/subsites as it is no longer included in cwp/cwp-installer
> API Include silverstripe/subsites

- composer.json
Need to tweak the version of framework test we install because of https://github.com/silverstripe/silverstripe-frameworktest/pull/70
> Target framework 4.x-dev on the sink

- composer.json
Mcrypt no longer exists in PHP7.4
> Remove mcrypt from dependencies
